#!/usr/bin/env bash

initPath="$HOME/.config/nvim"

#Check if silent mode
if [ "$1" == "-s" ]
then
	O="1>/dev/null 2>/dev/null"
else
	O=""
	echo "No silent mode"
fi

#Check if sudo is isntalled
if [ "$(which sudo | wc -c)" == 0 ]
then
	SU=""
else
	SU="sudo"
fi

#check if curl is not installed
if [ "$(which curl | wc -c )" == "0" ]
then
	$SU apt update && apt install curl -y
fi

#Check if nvim is not istalled
if [ "$(which nvim | wc -c )" == "0" ]
then
	$SU curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage $O
	$SU chmod +x nvim.appimage
	$SU ./nvim.appimage --appimage-extract $O
	$SU mkdir -p ~/bin
	$SU mv squashfs-root /
	$SU ln -s /squashfs-root/AppRun ~/bin/nvim

	#Check if ~/bin is in PATH variable
	if [[ ! ":$PATH:" =~ .*"$HOME/bin".* ]]
	then
		export PATH="$HOME/bin:$PATH"
	fi
fi

#Check if node.js is not isntalled or its version is less than 12.12
if [ "$(which node | wc -c)" == 0 ] || [ "$(node --version | sed 's/v\([[:digit:]]*\)\.\([[:digit:]]*\).*/\1\2/')" -lt 1212 ]
then
	curl -sL install-node.now.sh | bash 
fi

#Check if git is installed
if [ "$(which git | wc -c)" == 0 ]
then
	$SU apt-get update && apt-get pt-get install git-all -y $O
fi

#Create path for init.vim
mkdir -p "$initPath"
#Replace init.vim
rm -f "$initPath/init.vim"
ln -s "$(pwd)/src_vim_files/init.vim" "$initPath/init.vim"

#Replace .vimrc
rm -f ~/.vimrc
ln -s "$(pwd)/src_vim_files/.vimrc" "$HOME/.vimrc"
